### ISSUE TITLE
Deployment Modes and Out-of-Band Communication

### ISSUE THREAD

**Issue by eshaghoshms** [ietf-wg-keytrans/draft-arch#4]
The relation between the Deployment Modes and Out-of-Band Communication is a bit unclear. Is Out-of-Band Communication assumed for all Deployment Modes? For example, the Contact Monitoring Mode says it is "a single-party deployment with no third party". But this would not be sufficient to detect forking attacks unless some Out-of-Band Communication or Bulletin Board is assumed.

**Comment by Bren2010** [comment]
Out-of-Band Communication is available to detect forks in all deployment modes. Forking can still happen in the third-party modes if there's collusion

**Comment by eshaghoshms** [comment]
Thanks for the clarification! Can I suggest that we add this clarification in Section 5 as follows:

_In the interest of satisfying the widest range of use-cases possible, three different modes for deploying a Transparency Log are supported. Each mode has slightly different requirements and efficiency considerations for both the transparency log and the end-user._

to

_In the interest of satisfying the widest range of use-cases possible, three different modes for deploying a Transparency Log are supported. Each mode has slightly different requirements and efficiency considerations for both the transparency log and the end-user. **Note that Out-of-Band Communication is necessary to detect forks in all of these deployment modes.**_

**Comment by Bren2010** [comment]
Go for it
